"""Added role relation HR <-> Employee

Revision ID: 3e88e6987f8d
Revises: 721016a82f7e
Create Date: 2025-11-16 00:28:41.873165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e88e6987f8d'
down_revision: Union[str, Sequence[str], None] = '721016a82f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['hr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'hr_id')
    # ### end Alembic commands ###
