"""Additional error fixes in new fields User

Revision ID: 4299c4bef31a
Revises: 7c615f6823ac
Create Date: 2025-11-16 01:57:20.339364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4299c4bef31a'
down_revision: Union[str, Sequence[str], None] = '7c615f6823ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
