"""Updated table for RecommendationGuide

Revision ID: 721016a82f7e
Revises: eaec1712c25e
Create Date: 2025-11-15 19:04:01.543492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721016a82f7e'
down_revision: Union[str, Sequence[str], None] = 'eaec1712c25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendationguides', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('recommendationguides', sa.Column('title', sa.String(), nullable=False))
    op.add_column('recommendationguides', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('recommendationguides', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('recommendationguides', sa.Column('benefits', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('recommendationguides', sa.Column('is_actual', sa.Boolean(), nullable=False))
    op.add_column('recommendationguides', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('recommendationguides_label_key'), 'recommendationguides', type_='unique')
    op.create_unique_constraint(None, 'recommendationguides', ['title'])
    op.drop_column('recommendationguides', 'label')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendationguides', sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'recommendationguides', type_='unique')
    op.create_unique_constraint(op.f('recommendationguides_label_key'), 'recommendationguides', ['label'], postgresql_nulls_not_distinct=False)
    op.drop_column('recommendationguides', 'created_at')
    op.drop_column('recommendationguides', 'is_actual')
    op.drop_column('recommendationguides', 'benefits')
    op.drop_column('recommendationguides', 'category')
    op.drop_column('recommendationguides', 'summary')
    op.drop_column('recommendationguides', 'title')
    op.drop_column('recommendationguides', 'user_id')
    # ### end Alembic commands ###
