"""New fields from Excel data + new table - KPI

Revision ID: ddfe908fb13d
Revises: 3e88e6987f8d
Create Date: 2025-11-16 01:35:45.774071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfe908fb13d'
down_revision: Union[str, Sequence[str], None] = '3e88e6987f8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kpi_rate', sa.Float(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'recommendationguides', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('employment_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('last_vacation_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_sickness_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_participant_corp_activities', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_certified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_trained', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_trained')
    op.drop_column('users', 'is_certified')
    op.drop_column('users', 'is_participant_corp_activities')
    op.drop_column('users', 'last_sickness_at')
    op.drop_column('users', 'last_vacation_at')
    op.drop_column('users', 'employment_at')
    op.drop_constraint(None, 'recommendationguides', type_='foreignkey')
    op.drop_table('kpis')
    # ### end Alembic commands ###
