"""total_score field added to Metric

Revision ID: eaec1712c25e
Revises: 0bfaa6978f85
Create Date: 2025-11-15 17:32:28.965044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaec1712c25e'
down_revision: Union[str, Sequence[str], None] = '0bfaa6978f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('total_score', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics', 'total_score')
    # ### end Alembic commands ###
